# Write your MySQL query statement below
WITH T AS
(SELECT PLAYER_ID, MIN(EVENT_DATE) FIRST_LOGIN
FROM ACTIVITY GROUP BY PLAYER_ID),

T1 AS
(SELECT FIRST_LOGIN, COUNT(PLAYER_ID) INSTALLS
 FROM T GROUP BY FIRST_LOGIN),

T2 AS
(SELECT T.FIRST_LOGIN INSTALL_DT,
       SUM(IF(A.PLAYER_ID = T.PLAYER_ID AND A.EVENT_DATE-T.FIRST_LOGIN = 1, 1, 0)) RETENTION
FROM ACTIVITY A, T
GROUP BY INSTALL_DT)

SELECT T2.INSTALL_DT, T1.INSTALLS, ROUND(T2.RETENTION/T1.INSTALLS, 2) DAY1_RETENTION
FROM T2, T1
WHERE T2.INSTALL_DT = T1.FIRST_LOGIN
GROUP BY T2.INSTALL_DT