# Write your MySQL query statement below
WITH T AS
(SELECT PLAYER_ID, MIN(EVENT_DATE) FIRST_LOGIN
FROM ACTIVITY GROUP BY PLAYER_ID),

T2 AS
(SELECT T.FIRST_LOGIN INSTALL_DT,
       SUM(IF(A.PLAYER_ID = T.PLAYER_ID AND A.EVENT_DATE-T.FIRST_LOGIN = 1, 1, 0)) RETENTION
FROM ACTIVITY A, T
GROUP BY INSTALL_DT)

SELECT T2.INSTALL_DT, COUNT(T.PLAYER_ID) INSTALLS, ROUND(T2.RETENTION/COUNT(T.PLAYER_ID), 2) DAY1_RETENTION
FROM T2, T
WHERE T2.INSTALL_DT = T.FIRST_LOGIN
GROUP BY T2.INSTALL_DT