# Write your MySQL query statement below
WITH T1 AS
(SELECT ID, MONTH, SALARY
FROM
(SELECT ID, MONTH, SALARY,
ROW_NUMBER() OVER (PARTITION BY ID ORDER BY MONTH DESC) RECENT
FROM EMPLOYEE) T
WHERE RECENT > 1)

SELECT A.ID id, A.MONTH month, SUM(B.SALARY) Salary
FROM T1 A, T1 B
WHERE A.ID = B.ID AND B.MONTH BETWEEN A.MONTH - 2 AND A.MONTH
GROUP BY A.ID, A.MONTH