# Write your MySQL query statement below
SELECT T.ID, T.COMPANY, T.SALARY FROM
(SELECT ID, COMPANY, SALARY, 
ROW_NUMBER() OVER (PARTITION BY COMPANY ORDER BY SALARY, ID) RANKS,
COUNT(ID) OVER (PARTITION BY COMPANY) TTL
FROM EMPLOYEE) T
WHERE T.RANKS = CEILING(T.TTL/2) OR T.RANKS =  FLOOR(T.TTL/2) + 1