# Write your MySQL query statement below
SELECT ID, COMPANY, SALARY FROM
(SELECT ID, COMPANY, SALARY,
       ROW_NUMBER() OVER (PARTITION BY COMPANY ORDER BY SALARY ASC, ID ASC) AS ROW_ASC,
       ROW_NUMBER() OVER (PARTITION BY COMPANY ORDER BY SALARY DESC, ID DESC) AS ROW_DES
FROM EMPLOYEE) T
WHERE ROW_ASC BETWEEN ROW_DES - 1 AND ROW_DES + 1