# Write your MySQL query statement below
SELECT ROUND(AVG(T1.NUM), 1) MEDIAN FROM
(SELECT N1.NUM, SUM(N2.FREQUENCY) FREQ_ASC 
FROM NUMBERS N1, NUMBERS N2 
WHERE N1.NUM >= N2.NUM
GROUP BY N1.NUM) T1
LEFT JOIN 
(SELECT N1.NUM, SUM(N2.FREQUENCY) FREQ_DESC
FROM NUMBERS N1, NUMBERS N2
WHERE N1.NUM <= N2.NUM
GROUP BY N1.NUM) T2
ON T1.NUM = T2.NUM
LEFT JOIN NUMBERS N
ON T1.NUM = N.NUM
WHERE N.FREQUENCY >= ABS(T1.FREQ_ASC - T2.FREQ_DESC)
