# Write your MySQL query statement below
SELECT ROUND(AVG(N.NUM), 1) median FROM NUMBERS N,
(SELECT N.NUM, SUM(N1.FREQUENCY) LOW FROM NUMBERS N, NUMBERS N1 WHERE N.NUM >= N1.NUM GROUP BY N.NUM) NLOW,
(SELECT N.NUM, SUM(N2.FREQUENCY) HIGH FROM NUMBERS N, NUMBERS N2 WHERE N.NUM <= N2.NUM GROUP BY N.NUM) NHIGH
WHERE N.NUM = NLOW.NUM AND N.NUM = NHIGH.NUM AND N.FREQUENCY >= ABS(NLOW.LOW - NHIGH.HIGH)