# Write your MySQL query statement below
SELECT D.DEPT_NAME dept_name, COUNT(S.STUDENT_ID) student_number
FROM DEPARTMENT D
LEFT JOIN STUDENT S
ON D.DEPT_ID = S.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY STUDENT_NUMBER DESC, DEPT_NAME;