# Write your MySQL query statement below
WITH T AS (
SELECT P.PASSENGER_ID, MIN(B.ARRIVAL_TIME) AS BOARDING_TIME
FROM PASSENGERS P, BUSES B
WHERE P.ARRIVAL_TIME <= B.ARRIVAL_TIME
GROUP BY P.PASSENGER_ID
)

SELECT BUS_ID, COUNT(BOARDING_TIME) AS passengers_cnt
FROM BUSES
LEFT JOIN T
ON BOARDING_TIME = ARRIVAL_TIME
GROUP BY BUS_ID
ORDER BY BUS_ID;