# Write your MySQL query statement below
SELECT T.PLAYER_ID, T.DEVICE_ID FROM
(SELECT PLAYER_ID, DEVICE_ID, ROW_NUMBER() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) LOGIN
FROM ACTIVITY) T
WHERE LOGIN = 1