# Write your MySQL query statement below
SELECT A.PLAYER_ID, A.DEVICE_ID FROM ACTIVITY A, 
(SELECT PLAYER_ID, MIN(EVENT_DATE) FIRST_LOGIN
FROM ACTIVITY
GROUP BY PLAYER_ID) T
WHERE A.PLAYER_ID = T.PLAYER_ID
AND A.EVENT_DATE = T.FIRST_LOGIN