# Write your MySQL query statement below
SELECT ROUND(COUNT(A.PLAYER_ID)/COUNT(DISTINCT T.PLAYER_ID), 2) FRACTION FROM
(SELECT PLAYER_ID, MIN(EVENT_DATE) FIRST_LOGIN
FROM ACTIVITY
GROUP BY PLAYER_ID) T
LEFT JOIN ACTIVITY A
ON T.PLAYER_ID = A.PLAYER_ID AND T.FIRST_LOGIN = A.EVENT_DATE - 1