# Write your MySQL query statement below
SELECT ROUND(COUNT(DISTINCT T2.PLAYER_ID)/COUNT(DISTINCT T1.PLAYER_ID), 2) fraction
FROM 
(SELECT PLAYER_ID, MIN(EVENT_DATE) LOGIN FROM ACTIVITY GROUP BY PLAYER_ID) T1
LEFT JOIN ACTIVITY T2
ON T1.PLAYER_ID = T2.PLAYER_ID AND T1.LOGIN = T2.EVENT_DATE - 1