# Write your MySQL query statement below
SELECT ROUND(COUNT(*)/(SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2) FRACTION FROM
(SELECT PLAYER_ID, MIN(EVENT_DATE) FIRST_LOGIN
FROM ACTIVITY
GROUP BY PLAYER_ID) T, ACTIVITY A
WHERE T.PLAYER_ID = A.PLAYER_ID
AND T.FIRST_LOGIN = A.EVENT_DATE - 1