# Write your MySQL query statement below
SELECT D.NAME DEPARTMENT, T.NAME EMPLOYEE, T.SALARY FROM
(SELECT ID, NAME, SALARY, DEPARTMENTID,
       DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) RANKNUM
FROM EMPLOYEE) T
LEFT JOIN DEPARTMENT D
ON T.DEPARTMENTID = D.ID
WHERE T.RANKNUM <= 3