/* Write your T-SQL query statement below */
SELECT D.NAME Department, T.NAME Employee, T.SALARY Salary FROM
(SELECT NAME, SALARY, DEPARTMENTID, 
DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) RANKS
FROM EMPLOYEE) T
JOIN DEPARTMENT D
ON T.DEPARTMENTID = D.ID
WHERE T.RANKS = 1