# Write your MySQL query statement below
SELECT D.NAME Department, T.NAME Employee, T.SALARY Salary
FROM
(SELECT ID, NAME, SALARY, DEPARTMENTID,
       RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANKNUM
FROM EMPLOYEE) T
LEFT JOIN DEPARTMENT D
ON T.DEPARTMENTID = D.ID
WHERE RANKNUM = 1