# Write your MySQL query statement below
SELECT T.QUESTION_ID survey_log FROM
(SELECT QUESTION_ID, SUM(CASE ACTION WHEN "answer" THEN 1 ELSE 0 END)/SUM(CASE ACTION WHEN "show" THEN 1 ELSE 0 END) RATE
FROM SURVEYLOG
GROUP BY QUESTION_ID
ORDER BY RATE DESC, QUESTION_ID
LIMIT 1) T